// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200225182457_AddedConfigurationPcs")]
    partial class AddedConfigurationPcs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Entities.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("Core.Entities.ConfigurationComponent", b =>
                {
                    b.Property<Guid>("ConfigurationPcId");

                    b.Property<Guid>("ComponentId");

                    b.HasKey("ConfigurationPcId", "ComponentId");

                    b.HasIndex("ComponentId");

                    b.ToTable("ConfigurationComponents");
                });

            modelBuilder.Entity("Core.Entities.ConfigurationPC", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ConfigurationPCs");
                });

            modelBuilder.Entity("Core.Entities.ConfigurationComponent", b =>
                {
                    b.HasOne("Core.Entities.Component", "Component")
                        .WithMany("Configurations")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Entities.ConfigurationPC", "ConfigurationPC")
                        .WithMany("Components")
                        .HasForeignKey("ConfigurationPcId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
